### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML skeleton

- [x] Add CSS and JS pages, link to HTML

- [x] Select background color

- [x] Add car image
