### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x]  Add keydown event listener on document.

- [x]  Define a function to rotate car which:

- [x] Rotates the car left, if left arrow key is pressed
   
- [x] Rotates the car right, if right arrow key is pressed

- [x] Rotates up, if up key is pressed

- [x] Rotates down, if down key is pressed
