### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create a data model for the car.

- [x] Store the car's x and y coordinates in the data model.

- [x] Set a CSS property of position: absolute on the image.

- [x] Add a keydown eventListener to the document listening for the spacebar.

- [x] Create a function that moves the car forward.

- [x] Use the style property of element objects to change your car's top and left box offset styles.

- [x] Add an interval to move the car forward every 16 milliseconds when the spacebar is pressed.
