### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Adjust the right key listener so that if car is on, the car moves right.

- [x] Adjust the up key listener so that if the car is on, the car moves up.

- [x] Adjust the down key listener so that if the car is on, the car moves down.

- [x] Adjust the left key listener so that if the car is on, the car moves left.
